### PR TITLE
fix: duplicate push notification on subscribed user and territory

### LINKED ISSUE #1819: Duplicate(ish) push notifications for subscribed user and territory
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When stacker to whom you are subscribed posts in a territory to which you’re subscribed, you receive a push notification for each, e.g.:
1. User posted foo
2. user posted foo in bar territory 

These are deduped in the notifications page. They should also be deduped in push notifications. 

### Screenshots

I forgot to take one before clearing the notifications. 

### Steps To Reproduce

1. Enable push notifications
2. Subscribe to a user
3. subscribe to a territory
4. wait for the user to post in the territory 
5. see 2 notifications

### Expected behavior

Only 1 push notification should come through

### Logs

_No response_

### Device information

iOS PWA

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Soxasora**
## Description

Fixes #1819 
Adds a condition to the `notifyUserSubscribers`' query, ensuring that a push notification is not sent if the subscribed user has posted in a territory the recipient is subscribed to, avoiding duplicate notifications.

## Screenshots
before:
Image

after:
Image

## Additional Context
n/a

## Checklist

**Are your changes backwards compatible? Please answer below:**
Yes

**On a scale of 1-10 how well and how have you QA'd this change and any features it might affect? Please answer below:**
9, tested with userA and userB, the latter creating an Item in a territory user A is subscribed to

**For frontend changes: Tested on mobile, light and dark mode? Please answer below:**
n/a

**Did you introduce any new environment variables? If so, call them out explicitly here:**
No

### CODE REVIEW

File: lib/webPush.js [hunk 1]
```diff
@@ -137,6 +137,13 @@ export const notifyUserSubscribers = async ({ models, item }) => {
       AND "Reply"."ancestorUserId" = follower.id
       AND follower."noteAllDescendants"
     )
+    -- ignore subscription if user has posted to a territory the recipient is subscribed to
+    AND NOT EXISTS (
+      SELECT 1 FROM "SubSubcription"
```
Comment (ekzyis) [inline lib/webPush.js:142]: :eyes: 

```suggestion
      SELECT 1 FROM "SubSubscription"
```

File: lib/webPush.js [hunk 2]
```diff
@@ -137,6 +137,13 @@ export const notifyUserSubscribers = async ({ models, item }) => {
...
+      INNER JOIN "Item" ON "Item"."subName" = "SubSubscription"."subName"
+      WHERE "SubSubscription"."userId" = "UserSubscription"."followerId"
+      AND "Item"."userId" = $1
+    )
     `, Number(item.userId), Number(item.id))
```
Comment (ekzyis) [inline lib/webPush.js:147]: I don't think you need this join, you can use `item.subName` as `$3` to get the territory and then use this filter:

```suggestion
      WHERE "SubSubscription"."userId" = "UserSubscription"."followerId"
      AND "SubSubscription"."subName" = $3
    )
    `, Number(item.userId), Number(item.id), item.subName)
```

**Review by ekzyis — CHANGES_REQUESTED** [review]
Perfect location for the fix, but I noticed three things:

1. Syntax error that I assume went unnoticed because a syntax error also results in no push notification as expected :eyes:
2. unnecessary join?
3. this also prevents the push notification for comments but the conflicting subscription for territories only handles posts

For 3., you could add the following to the subquery:

```sql
AND ${isPost ? 'true' : 'false'}
```

but maybe you have a better idea

File: lib/webPush.js (hunk 1 above)
Comment (Soxasora) [reply lib/webPush.js:142]: embarrassed to say the least 🫠

File: lib/webPush.js (hunk 2 above)
Comment (Soxasora) [reply lib/webPush.js:147]: Added an isPost to $3 because comments don't have a subName

**Comment by Soxasora** [comment]
Thank you ek, your review is spot on and my mind wasn't at the time, sorry about that.
Comments now show up and duplicate notifications are gone!

**Comment by huumn** [comment]
I modified the query to use [prisma's tagged template helpers](https://www.prisma.io/docs/orm/prisma-client/using-raw-sql/raw-queries#tagged-template-helpers). We wrote a lot of these queries before prisma supported these tagged template fragments. In general, when we're modifying queries these days, I like to move away from `queryRawUnsafe` when I can - harder to mess up.
