### PR TITLE
fix duplicate search highlights

### LINKED ISSUE #2181: Search highlights are duplicated
https://stacker.news/items/988711/r/k00b

### PR DESCRIPTION
**Pull request by abhiShandy**
## Description

_A clear and concise description of what you changed and why._

fixes #2181 

Avoid including both exact matches and item text in search results.

## Screenshots

Before
before

After
after

## Additional Context

_Was anything unclear during your work on this PR? Anything we should definitely take a closer look at?_

## Checklist

**Are your changes backwards compatible? Please answer below:**
Yes

**On a scale of 1-10 how well and how have you QA'd this change and any features it might affect? Please answer below:**
10

**For frontend changes: Tested on mobile, light and dark mode? Please answer below:**
Tested on laptop only

**Did you introduce any new environment variables? If so, call them out explicitly here:**
No

### CODE REVIEW

**Review by ekzyis — APPROVED** [review]
Change to fix duplicate search highlights makes sense to me, but I didn't test

File: api/resolvers/search.js [hunk 1]
```diff
@@ -510,7 +510,7 @@ export default {
         item.searchTitle = e.highlight?.title?.[0] || e.highlight?.['title.exact']?.[0] || item.title
 
         // prefer the exact highlight for text
-        const searchTextHighlight = [...(e.highlight?.['text.exact'] || []), ...(e.highlight?.text || [])]
+        const searchTextHighlight = [...(e.highlight?.['text.exact'] || e.highlight?.text || [])]
```
Comment (huumn) [inline api/resolvers/search.js]: You don't need all the spreads if you're just taking one.

File: api/resolvers/search.js [hunk 2]
```diff
@@ -510,7 +510,7 @@ export default {
...
         item.searchText = searchTextHighlight?.slice(0, 5)?.join(' ... ')
```
Comment (huumn) [inline api/resolvers/search.js]: You don't need this slice, because now there's never more than 5.

**Review by huumn — CHANGES_REQUESTED** [review]

File: api/resolvers/search.js (hunk 2 above)
Comment (abhiShandy) [reply api/resolvers/search.js]: done

File: api/resolvers/search.js (hunk 1 above)
Comment (abhiShandy) [reply api/resolvers/search.js]: done
