### PR TITLE
Handle uploads in territory descriptions

### LINKED ISSUE #2378: uploaded images in territory descriptions don't load
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

The following uploaded images are included in territory descriptions and don't load because of 403 Forbidden:

- https://m.stacker.news/49659 (~bitcoin_beginners)
- https://m.stacker.news/15191 (~Photography)
- https://m.stacker.news/86601 (~Stacker_Sports)
- https://m.stacker.news/16171 (~privacy)
- https://m.stacker.news/7551 (~chess)
- https://m.stacker.news/7458 (~Value4Value)
- https://m.stacker.news/7572 (~earth)

But there are also uploaded images in territory descriptions that do load:

- https://m.stacker.news/7518 (~libertarian)
- https://m.stacker.news/15897 (~oracle)
- https://m.stacker.news/101605 (~AGORA)

I think we might be deleting images that are only included in territory descriptions and not paid.

### Screenshots

_No response_

### Steps To Reproduce

???

### Expected behavior

all images load

### Logs

_No response_

### Device information

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ekzyis**
## Description

fix #2378 

- move check for expired uploads into reusable function
- mark uploads as paid when territories are created or updated
- include upload fees on territory create and update

## Additional Context

1. I considered not including upload fees since I still worry about breaking something even after annoying testing and not that important imo for territories (let founders have an obscure way to get free uploads) but felt like a cop out, so I added and tested it anyway

2. ~I think the check for expired uploads should also run on edits~ changed my mind, included it in this PR

3. See https://github.com/stackernews/stacker.news/pull/2379#discussion_r2248849545

## Checklist

**Are your changes backward compatible? Please answer below:**

yes

**On a scale of 1-10 how well and how have you QA'd this change and any features it might affect? Please answer below:**

`9`

**For frontend changes: Tested on mobile, light and dark mode? Please answer below:**

n/a

**Did you introduce any new environment variables? If so, call them out explicitly here:**

no

### CODE REVIEW

File: lib/territory.js [hunk 1]
```diff
@@ -19,7 +19,7 @@ export function purchasedType (sub) {
 export function proratedBillingCost (sub, newBillingType) {
   if (!sub ||
     sub.billingType === 'ONCE' ||
-    sub.billingType === newBillingType.toUpperCase()) return null
+    sub.billingType === newBillingType.toUpperCase()) return 0
```
Comment (ekzyis) [inline lib/territory.js:22]: not sure why this returned `null` instead of 0 (historical reasons?), but it's only used on territory update and afaict, it's safe to return 0

File: api/paidAction/territoryUpdate.js [hunk 2]
```diff
@@ -63,6 +62,18 @@ export async function perform ({ oldName, invoiceId, ...data }, { me, cost, tx }
...
+      where: {
+        id: { in: data.uploadIds }
+      },
+      data: {
+        paid: true
+      }
+    })
+  }
+  delete data.uploadIds
+
```
[the remark this answers is not in the document]
Comment (ekzyis) [reply api/paidAction/territoryUpdate.js:77]: done in d8ad6b68

File: api/resolvers/upload.js [hunk 3]
```diff
@@ -68,3 +68,15 @@ export async function uploadFees (s3Keys, { models, me }) {
...
   return { ...info, uploadFees, totalFees, totalFeesMsats }
 }
+
+export async function throwOnExpiredUploads (uploadIds, { tx }) {
+  const deletedUploads = []
+  for (const uploadId of uploadIds) {
+    if (!await tx.upload.findUnique({ where: { id: uploadId } })) {
+      deletedUploads.push(uploadId)
+    }
+  }
```
Comment (huumn) [inline api/resolvers/upload.js]: is there a way to do this that doesn't require a round trip for every image?

File: api/resolvers/sub.js [hunk 4]
```diff
@@ -210,6 +211,8 @@ export default {
 
       await validateSchema(territorySchema, data, { models, me, sub: { name: data.oldName } })
 
+      data.uploadIds = uploadIdsFromText(data.desc)
+
```
Comment (huumn) [inline api/resolvers/sub.js:215]: doesn't `uploadIdsFromText` return a promise? I'm surprised this works

File: api/paidAction/territoryUpdate.js [hunk 5]
```diff
@@ -11,18 +12,16 @@ export const paymentMethods = [
...
     }
   })
 
-  const cost = proratedBillingCost(oldSub, billingType)
-  if (!cost) {
-    return 0n
-  }
+  const { totalFees } = await uploadFees(uploadIds, { models, me })
 
+  const cost = proratedBillingCost(oldSub, billingType) + totalFees
```
Comment (huumn) [inline api/paidAction/territoryUpdate.js:24]: Do we surface this cost in `FeeButton` for the territory payment/update?

File: api/resolvers/upload.js (hunk 3 above)
Comment (ekzyis) [reply api/resolvers/upload.js]: Right, got confused how to return _deleted_ ids in a query but I realized deleted = uploads - existing lol

Done in 342e3423

File: api/paidAction/territoryUpdate.js (hunk 5 above)
Comment (ekzyis) [reply api/paidAction/territoryUpdate.js:24]: Yes, tested by manually returning `1000` for `totalFees`:

```diff
diff --git a/api/resolvers/upload.js b/api/resolvers/upload.js
index 9b012af1..ea8b6425 100644
--- a/api/resolvers/upload.js
+++ b/api/resolvers/upload.js
@@ -66,7 +66,7 @@ export async function uploadFees (s3Keys, { models, me }) {
   const uploadFees = msatsToSats(info.uploadFeesMsats)
   const totalFeesMsats = info.nUnpaid * Number(info.uploadFeesMsats)
   const totalFees = msatsToSats(totalFeesMsats)
-  return { ...info, uploadFees, totalFees, totalFeesMsats }
+  return { ...info, uploadFees, totalFees: 1000, totalFeesMsats }
 }

 export async function throwOnExpiredUploads (uploadIds, { tx }) {
```

2025-08-02-022819_1920x1080_scrot
