### PR TITLE
Fix no red square for territory posts

### LINKED ISSUE #1164: No red square pop-up when a new post appears in a territory I've subscribed to
**Description**
Not getting the red square on the notification bell upon a new post in a subscribed territory.

**Steps to Reproduce**
Sub to territory, wait for post in said territory.

**Expected behavior**
Red square upon new post, like when a subscribed stacker posts something.

**Screenshots**
Today I subbed to a couple extra territories to be sure of the bug, no red square when these were posted.
image

---
The screenshot below did have a red square, because of the subscribed stacker
---
image

**Environment:**
Browser (Brave and Chrome) and PWA

**Additional context**
Has been doing this to me for a while actually:

https://stacker.news/items/441695/r/OneOneSeven?commentId=442970
https://stacker.news/items/430488/r/OneOneSeven?commentId=430959

### PR DESCRIPTION
**Pull request by ekzyis**
## Description

Closes #1164

## Checklist

**Are your changes backwards compatible? Please answer below:**

Yes

**Did you QA this? Could we deploy this straight to production? Please answer below:**

Yes

**For frontend changes: Tested on mobile? Please answer below:**

**Did you introduce any new environment variables? If so, call them out explicitly here:**

### CODE REVIEW

File: api/resolvers/user.js [hunk 1]
```diff
@@ -311,6 +311,22 @@ export default {
...
+        SELECT EXISTS(
+          SELECT *
+          FROM "SubSubscription"
+          JOIN "Item" ON "SubSubscription"."subName" = "Item"."subName"
+          ${whereClause(
+            '"SubSubscription"."userId" = $1',
+            '"Item".created_at > $2',
+            '"Item"."parentId" IS NULL',
+            await filterClause(me, models),
+            muteClause(me))})`, me.id, lastChecked)
```
Comment (ekzyis) [inline api/resolvers/user.js:324]: This will need `statusClause` when #1184 is merged
