### PR TITLE
Fix pending forwards considered paid by client

### LINKED ISSUE #1707: Client considers some possible invoice states of failed forwards as paid
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Polling a wrapped invoice at the wrong time leads the client to believe the invoice was paid because `inv.satsReceived > 0` and the invoice polling code detected no error.

### Screenshots

https://github.com/user-attachments/assets/c7933cdb-0a29-45d2-b9f1-e6deb482088b

### Steps To Reproduce

1. p2p zap someone
2. get unlucky
3. see invoice was considered paid but the forward actually failed 

### Expected behavior

any invoice that is in some failed state is detected as failed and not as paid by the client

### Logs

_No response_

### Device information

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ekzyis**
## Description

Fix #1707 

This excludes pending forwards from ever being considered for something by the client.

I think this is a change that should really only affect the bug regarding failed forwards and doesn't cause any regression during other payments.

## Additional Context

Maybe the server should set a `pending` field in the invoice which the client can use to know that it shouldn't use this state to determine something about the invoice? I don't like how the client becomes more aware of individual transitions because it _might_ see them just so it can ignore them. 

## Checklist

**Are your changes backwards compatible? Please answer below:**

yes

**On a scale of 1-10 how well and how have you QA'd this change and any features it might affect? Please answer below:**

`7`.  Tested with failed forwards, successful forwards and no forwards. The bug is easy to trigger without these changes and this patch:

```diff
diff --git a/wallets/payment.js b/wallets/payment.js
index 33baa717..db8c9883 100644
--- a/wallets/payment.js
+++ b/wallets/payment.js
@@ -123,7 +123,7 @@ function invoiceController (inv, isInvoice) {
           clearInterval(interval)
           signal.removeEventListener('abort', abort)
         }
-      }, FAST_POLL_INTERVAL)
+      }, 100)

       const abort = () => {
         console.info(`invoice #${inv.id}: stopped waiting`)
diff --git a/worker/paidAction.js b/worker/paidAction.js
index 70396ddb..9d711b0f 100644
--- a/worker/paidAction.js
+++ b/worker/paidAction.js
@@ -268,7 +268,7 @@ export async function paidActionForwarding ({ data: { invoiceId, ...args }, mode
     payViaPaymentRequest({
       lnd,
       request: bolt11,
-      max_fee_mtokens: String(maxFeeMsats),
+      max_fee_mtokens: String(0),
       pathfinding_timeout: LND_PATHFINDING_TIMEOUT_MS,
       max_timeout_height: maxTimeoutHeight
     }).catch(console.error)
```

**For frontend changes: Tested on mobile, light and dark mode? Please answer below:**

n/a

**Did you introduce any new environment variables? If so, call them out explicitly here:**

no

### CODE REVIEW

File: components/use-invoice.js [hunk 1]
```diff
@@ -16,24 +18,29 @@ export default function useInvoice () {
...
     const expired = cancelledAt && new Date(expiresAt) < new Date(cancelledAt)
     if (expired) {
       throw new InvoiceExpiredError(data.invoice)
     }
 
-    const failed = cancelled || actionError
-
-    if (failed && (forwardStatus && forwardStatus !== 'CONFIRMED')) {
+    const failedForward = forwardStatus && forwardStatus !== 'CONFIRMED'
+    if (failedForward) {
```
Comment (ekzyis) [inline components/use-invoice.js:29]: Removing `failed` from the condition for failed forwards makes this resolve a little faster since the withdrawal can already have failed before the invoice itself is marked as failed, see video in https://github.com/stackernews/stacker.news/issues/1707#issuecomment-2535829482.

**Comment by huumn** [comment]
Why not just change `waitFor = i => actionState === 'PAID'` in the case of send wallet being present?

**Comment by ekzyis** [comment]
I thought it's okay to assume that `useInvoice` is only used in the case of send wallets so we can hide the complexity in there and that's also why I thought that is reasonable limiting of `waitFor`.

> ... `waitFor` should maybe be refactored somehow though. It's not clear where the function is coming from and most of the time we're using a default param from somewhere else in the code base.

I agree, good time to also refactor `useInvoice` as you mentioned in the past. But I would rather fix this without a refactor first so this doesn't block a release.

I'll fix this in `useAct` the way you described it. I'll keep `waitFor` in `useQrPayment` as-is since it doesn't affect this bug but is related to #1712.
