### PR TITLE
fix: avoid image/video layout shifts

### LINKED ISSUE #2700: images cause vertical layout shift
I'm noticing that nearly all images cause vertical layout shift now. This has always been a bit of a war, ie never worked in all situations consistently. It'd be nice to solve it once and for all.

### PR DESCRIPTION
**Pull request by Soxasora**
## Description

Fixes #2700
This PR aims at overhauling Media to prevent layout shifts and provide a better error/loading experience.

- If we know the dimensions (imgproxy processing), the `sn-media` container will be the one responsible for occupying space for the child image, avoiding layout shift.
  - If we don't know the dimensions, we have to deal with the legacy behavior of waiting for the image to load to occupy space (layout shift!)
- The `lexicalState` is now a string rather than a `JSONObject`, preventing lexical reader double render (that also caused layout shifts)
  - The `useMemo` here should've prevented re-renders because `lexicalState` doesn't actually change, but there's a reference mismatch between the `state` we pass via SSR and the `state` we merge from Apollo cache that causes re-renders (object ref comparison fails). By making `lexicalState` a string useMemo is able to do string comparison instead, fixing re-renders because the content is the same.
- On item create/update, uploads populate the `imgproxyUrls` field with preliminary data (dimensions, type). This eliminates layout shifts on items that didn't get processed by imgproxy yet, especially noticeable on create/update.

## Screenshots

Autolink media check

https://github.com/user-attachments/assets/6f1cd0a8-6207-4e0f-9e86-28606530c8af

- If an autolink is not detected as an item mention or an embed, a spinning moon appears to indicate we are doing media checks.

---

Loading images with known dimensions (slowed down for demonstration purposes)

https://github.com/user-attachments/assets/d5019a14-f1d5-4299-9103-8016f14a85b7

- Media now shows a loading placeholder while the image/video loads (using `onLoad`)
  - sometimes loading is so fast that the loading placeholder can be a flash, for this reason it starts with `opacity:0` fading into `opacity:1` in 1 second.

---

Content not available (fetch error)
image

- An image can get deleted, a service or imgproxy might not be available, in these cases we can provide an error placeholder that retains the dimensions we know
  - an harmless option was to render a link in this case, rather than wasting space with the error placeholder. but errors that come from trying to load the image are a cause of layout shift (image loads, errors, returns to a link)

## Additional Context

`lexicalState` being a `JSONObject` caused the Lexical Reader to re-render due to SSR->Apollo reference mismatches, to fix this the `lexicalState` is now a string.

## Checklist

**Are your changes backward compatible? Please answer below:**

_For example, a change is not backward compatible if you removed a GraphQL field or dropped a database column._
n/a
**On a scale of 1-10 how well and how have you QA'd this change and any features it might affect? Please answer below:**
6 - in dev, in qa

**For frontend changes: Tested on mobile, light and dark mode? Please answer below:**
tbd

**Did you introduce any new environment variables? If so, call them out explicitly here:**
n/a

**Did you use AI for this? If so, how much did it assist you?**
No, tried without success

---

> [!NOTE]
> Addresses layout shifts and improves media UX across create, update, render, and style layers.
> 
> - Pre-populate `imgproxyUrls` during item create/update via `getTempImgproxyUrls`, using upload `width/height/type` to reserve space
> - GraphQL: change `lexicalState` from `JSONObject` to `String` in `Item`, `Bulletin`, and `Sub` to avoid reader re-renders
> - Media rendering overhaul: new `MediaOrLink` in editor nodes with loading placeholders, error fallback, carousel integration, legacy `srcSet` handling, and scroll preservation; remove old `components/media-or-link.js`
> - Lexical updates: refined `MediaNode`/`EmbedNode` `exportDOM`, merge adjacent media into galleries in `GalleryExtension`, server interpolator returns stringified editor state
> - Embeds: replace `react-youtube` with lightweight `react-lite-youtube-embed`; unify classes; CSP `frame-src` includes `www.youtube-nocookie.com`
> - File upload captures `videoWidth/videoHeight`; `Text` recalculates overflow on media load; `preserve-scroll` is SSR-safe no-op
> - Styling: extensive `sn-media`/embed CSS refinements; new icons; dependencies updated (add `react-lite-youtube-embed`, drop `react-youtube`)
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit ebe3ae3c12b1c075f4c96692d1aa83482072b83b. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by Soxasora** [comment]
```
standard: Run `standard --fix` to automatically fix some problems.
  /home/runner/work/stacker.news/stacker.news/components/seo.js:45:14: Strings must use singlequote. (quotes)
```

Didn't even touch `seo.js` 🤨

File: api/payIn/lib/upload.js [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+ * pre-populate imgproxyUrls with upload dimensions and type for new uploads
+ *
+ * the imgproxy job will overwrite these with the actual imgproxy URLs and data
+ *
+ * @param models - db prisma models or transaction
+ * @param uploadIds - array of upload IDs
+ * @param oldImgproxyUrls - optional existing imgproxyUrls object to merge with
+ * @returns initial imgproxyUrls object with upload dimensions and type
+ */
+export async function getTempImgproxyUrls (models, uploadIds, oldImgproxyUrls) {
```
Comment (Soxasora) [inline api/payIn/lib/upload.js:11]: `imgproxyUrls` in the db can be `mediaData` at this point, but for the moment we can maybe skip migrations and reserve this for a future normalization?

**Comment by huumn** [comment]
rather than a spinning icon, can we just make the link text pulse? it's more subtle, especially when it just ends up being a link

**Comment by Soxasora** [comment]
stealth 🥷

https://github.com/user-attachments/assets/58e39fa3-73da-4422-95e6-25e7dd07a8e2

<sup>network slowed down for demonstration purposes</sup>

File: styles/text.scss [hunk 2]
```diff
@@ -199,13 +219,49 @@
...
+}
+
+// image can load very fast, fade in to avoid flashing
+@keyframes fadeIn {
+  from {
+    opacity: 0;
+  }
+  to {
+    opacity: 1;
+  }
```
[the remark this answers is not in the document]
Comment (Soxasora) [reply styles/text.scss:287]: oh shoot! I thought I was forgetting something!

File: components/editor/nodes/media.js [hunk 3]
```diff
@@ -1,10 +1,104 @@
...
+  return (
+    <LinkRaw rel={rel} src={src}>
+      {width && height && (
+        <div className='sn-media__error'>
+          <FileError />
+          <p>
+            content not available
+            <br />
+            <span className='fw-medium'>
+              view original <sup><ExternalLink width={14} height={14} /></sup>
```
Comment (Soxasora) [inline components/editor/nodes/media.js]: maybe `view original` is not a really straightforward choice of words here

Comment (huumn) [reply components/editor/nodes/media.js]: I would just show the link as it is, e.g. `https://i.imgur.com/lkSMkZw.jpeg`

Comment (Soxasora) [reply components/editor/nodes/media.js]: In the error container or literally show the link if media can't be loaded? For the latter, the problem was that for images with known dimensions we're doing inverse layout shift (big -> small)

Comment (huumn) [reply components/editor/nodes/media.js]: i meant show it in the container because i figured they were there for layout shift reasons

**Comment by huumn** [comment]
Something prevents 'show full text' when a post is long and has many auto-link images (on the first write-preview): https://stacker.news/items/1412591/edit 

After the image is cached (I go preview->write->preview), 'show full text' appears.

**Comment by huumn** [comment]
On the same post, the autolink images still cause shift (which is not a regression), but if these changes make fixing this easier, it may be worth adding.

**Comment by Soxasora** [comment]
> Something prevents 'show full text' when a post is long and has many auto-link images 

Happens on Chromium but not Safari, this is interesting. On it!

> the autolink images still cause shift (which is not a regression), but if these changes make fixing this easier, it may be worth adding

The thing with image autolinks is that we don't have the dimensions of them until the image is actually loading. It's tricky to do it without waiting for the proxied url, but I'll explore more.

**Comment by huumn** [comment]
> The thing with image autolinks is that we don't have the dimensions of them until the image is actually loading.

This happens for me even after the images are proxied.

**Comment by huumn** [comment]
As usual, if you can't recreate some of this might be an issue with my local setup.

I also do not get the placeholders with ``. I haven't tried direct uploads yet

**Comment by huumn** [comment]
I'm not seeing placeholders even for the images I upload. (I've disabled caching if that's relevant.)

Also, I'm not sure if it's related but initial media checks get cancelled before succeeding.

Screenshot 2026-01-16 at 1 06 58 PM

**Comment by Soxasora** [comment]
> I also do not get the placeholders with ``

Here too the placeholder should appear only for proxied images because of unknown dimensions
(horizontal shift due to scrollbar, on this we may want to explore [`scrollbar-gutter`](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Properties/scrollbar-gutter))

Original:


https://github.com/user-attachments/assets/666cec27-d95c-4e2c-9956-ab4e4048d912



Proxied:

https://github.com/user-attachments/assets/f5bf2f78-2776-4a66-8b41-f7aa4d8789fd

**Comment by Soxasora** [comment]
> I'm not seeing placeholders even for the images I upload.

I can't reproduce the absent placeholder bug, on uploads we now even populate `imgproxyUrls` to give the dimensions to lexical (`LexicalItemContext`). Can you see the dimensions in the cache/db?

**Comment by huumn** [comment]
https://github.com/user-attachments/assets/a09555ab-233c-46d4-b44c-018a1b8050b8

**Comment by Soxasora** [comment]
image

image

It seems like your lexical is exporting and rendering the `MediaNode` without width, height and type, only the `srcSet` mhh...

**Comment by huumn** [comment]
Ah, i'm probably not running imgproxy pro. i'm sorry. i think i did this last time too.

**Comment by Soxasora** [comment]
Ah!! Well that also explains uploads, because imgproxy replaces the object in the db... so it replaces also the dimensions we got from the upload process lol

**Comment by huumn** [comment]
With pro, QA is strong. I'll give the code a review before EoD.

**Comment by huumn** [comment]
https://github.com/user-attachments/assets/9444fff8-4916-4144-89c1-5fa871c5fa66

YouTube embeds do not seem to reserve vertical space

**Comment by Soxasora** [comment]
Ah, embeds are not contemplated at all in this PR. The fact that embeds would need a better styling and better relationship with Lexical made me think that they deserves its own PR, but I can draft this and extend it! Sorry I got hyperfixated on media that I didn't prioritize embeds :/

**Comment by huumn** [comment]
All good. For some reason I lumped them together

**Comment by Soxasora** [comment]
It's quite calm to enter a page without layout shifts. The only time we should encounter layout shifts is with unproxied autolinks, everything else should be stable.

I'm going to continue QA with different use-cases, and find ways to clean this up. But other than these two things, this should be ready to go.

edit: I'll wait cursorbot tips, it's being really helpful

**Comment by huumn** [comment]
QA is good. I'm still seeing spinners but we can merge/deploy this if you'd prefer to wait to do that.

I'll do another pass over the code too

File: lib/lexical/nodes/content/embed.jsx [hunk 4]
```diff
@@ -92,28 +92,35 @@ export class EmbedNode extends DecoratorBlockNode {
...
-      } catch {
-        link.textContent = 'view on ' + this.__provider
-      }
-      container.append(link)
-    }
+    wrapper.append(container)
+    decorator.append(wrapper)
 
-    return { element: container }
+    return { element: decorator }
```
[the remark this answers is not in the document]
Comment (Soxasora) [reply lib/lexical/nodes/content/embed.jsx:123]: Lexical should traverse nested nodes, the extra divs are there for fast css selector consistency

**Comment by Soxasora** [comment]
Found some sizing issues on `MediaError` and layout shifts caused by autolinks grouped in a `GalleryNode`. I'll fix them ASAP

File: lib/lexical/exts/gallery.js [hunk 5]
```diff
@@ -30,31 +35,54 @@ export const GalleryExtension = defineExtension({
...
+        }
+
+        // merge all media into the gallery
+        for (const item of collected) {
+          if (item.node !== gallery) {
+            const mediaNodes = item.node.getChildren().filter($isMediaNode)
+            for (const media of mediaNodes) gallery.append(media)
+            item.node.remove()
+          }
+        }
```
[the remark this answers is not in the document]
Comment (Soxasora) [reply lib/lexical/exts/gallery.js:86]: Yes that's what I'm encountering in QA too, fixing this.
