### PR TITLE
Fix new comments navigator duplicate counts

### LINKED ISSUE #2606: Uncollapsing a new comment re-tracks it
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Every time a new comment is uncollapsed, the navigator re-tracks it, increasing the count of new comments.

### Screenshots

https://github.com/user-attachments/assets/047fe6c0-09a3-49b4-a3a4-f0ad183ca491

courtesy of @ekzyis 

### Steps To Reproduce

1. Go to a thread with new comments
2. Collapse the thread
3. Uncollapse the thread
4. Navigator tracks the same comment(s) again

### Expected behavior

Navigator shouldn't track already tracked comments

### Logs

_No response_

### Device information

_No response_

### Additional context

Reported by @ekzyis

### PR DESCRIPTION
**Pull request by Soxasora**
## Description

Fixes #2606 
When navigator receives a new comment ref, the deduplication process only checks if the exact ref received is already present in the commentRefs array. When a comment gets collapsed and uncollapsed, its ref dies and the comparison would just fail.

The fix involves making the comment counter aware of stale (disconnected) refs and refreshing it on every action.
This way, the navigator gets rid of stale refs and the counter will always be truthful to what is shown to the user; fixing duplicate counts (collapsing and uncollapsing), and stale counts (collapsing).

## Screenshots

tbd

## Additional Context

This is another reminder for me to refactor the outlining system, since the outlining effect shouldn't run on every collapse/uncollapse.

## Checklist

**Are your changes backward compatible? Please answer below:**

_For example, a change is not backward compatible if you removed a GraphQL field or dropped a database column._
Yes

**On a scale of 1-10 how well and how have you QA'd this change and any features it might affect? Please answer below:**
7, scrolling to a comment, collapsing and uncollapsing works correctly.

**For frontend changes: Tested on mobile, light and dark mode? Please answer below:**
n/a

**Did you introduce any new environment variables? If so, call them out explicitly here:**
n/a

**Did you use AI for this? If so, how much did it assist you?**
no

---

> [!NOTE]
> Make the comments navigator robust to disconnected refs and add cleanup to untrack comments, ensuring accurate new-comment counts.
> 
> - **Comments Navigator (`components/use-comments-navigator.js`)**:
>   - Filter out disconnected refs before counting in `throttleCountUpdate`.
>   - In `untrackNewComment`, update count even if the ref is missing; always call `throttleCountUpdate` after processing.
>   - In `scrollToComment`, handle missing nodes by triggering a count refresh; update dependencies.
> - **Comment component (`components/comment.js`)**:
>   - Add cleanup to `useEffect` to call `navigator.untrackNewComment(ref, { includeDescendants: true })` when effect cleans up, preventing stale tracking.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 1d0c3e53cb7fecbeaded529992adfdaa14f9fd48. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: components/comment.js [hunk 1]
```diff
@@ -187,6 +187,10 @@ export default function Comment ({
     }
 
     navigator.trackNewComment(ref, itemCreatedAt)
+
+    return () => {
+      navigator.untrackNewComment(ref, { includeDescendants: true })
+    }
```
Comment (Soxasora) [inline components/comment.js:193]: I thought of a simpler way to fix this: we can untrack the comment on unmount (which collapsing does) and add a check for disconnected refs in the comment counter.

This way, every time there's an invalid ref being passed, or an action, the navigator cleans itself from stale refs.
