### PR TITLE
enhance: support rich pastes in markdown mode

### LINKED ISSUE #2833: Mode-aware copy/paste
For a better copy/paste experience, we can start by transforming the copied content into the destination format, e.g. Lexical<->Markdown.

### LINKED ISSUE #2867: Pasting in markdown mode is not reliable
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Copy and paste doesn't paste all the highlighted text.

### Screenshots

https://github.com/user-attachments/assets/c531e0e0-4503-4541-af01-a1da83aaa0c1

### Steps To Reproduce

See recording above.

### Expected behavior

All highlighted text should be copy and pasted.

### Logs

_No response_

### Device information

Windows / Brave

### Additional context

Not that easily reproducible.  I think it has to do with a hidden character.  Sometimes when I highlight the line it gets pasted, at other times not.

### PR DESCRIPTION
**Pull request by Soxasora**
## Description

Fixes #2867 
Closes #2833 

`MarkdownPastePlugin` redirects markdown mode paste events to the **rich text bridge**, leveraging Lexical’s rich paste handler that supports HTML and Lexical rich nodes. Consequently, the resulting bridge editor state is converted into markdown using MDAST and inserted back into the original markdown mode editor.

## Screenshots

https://github.com/user-attachments/assets/12754717-9980-4712-8887-b993d92ab48c

## Additional Context

The redirect approach is probably the most straightforward as everything is handled by Lexical. The alternative involved implementing custom copy/paste handlers for markdown mode and rich mode, with support for markdown already on copy ... but it's really not needed.

## Checklist

**Are your changes backward compatible? Please answer below:**
Yes, now headless bridges spawn by default with `sn-rich` namespace but its only purpose is to handle direct Lexical rich nodes paste, doesn't affect anything else.

**On a scale of 1-10 how well and how have you QA'd this change and any features it might affect? Please answer below:**
7, always falls back to plain text if Lexical, then HTML, payloads are not available.

**Did you use AI for this? If so, how much did it assist you?**
Minimally, just to inspect what goes on inside `@lexical/clipboard`

---

> [!NOTE]
> **Medium Risk**
> Changes clipboard/paste handling in markdown mode by intercepting `PASTE_COMMAND` and routing it through a headless rich-text bridge, which could affect paste behavior and formatting edge cases across browsers.
> 
> **Overview**
> Markdown-mode pastes are now intercepted and converted via a headless rich-text “bridge” editor: the paste event is dispatched to the bridge (allowing Lexical HTML/rich-node paste handling), exported back to markdown via MDAST, then inserted into the markdown editor.
> 
> The headless bridge hook now supports a configurable `namespace` and defaults to `sn-rich` to enable compatible rich paste/copy behavior when reusing Lexical’s clipboard pipeline.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 82ccaa77e7a3fae7f8eaa2c1d6d521d4d7185fb2. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: components/editor/plugins/core/markdown-paste.js [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+    root.selectEnd()
+  })
+
+  // redirect the original paste event to the bridge
+  bridge.dispatchCommand(PASTE_COMMAND, event)
+
+  // export the resulting nodes as markdown
+  let markdown = ''
+  bridge.update(() => {
+    markdown = $lexicalToMarkdown(true)
```
[the remark this answers is not in the document]
Comment (Soxasora) [reply components/editor/plugins/core/markdown-paste.js]: Hmm, well, that's a good point. I'll re-enable escapes.

File: components/editor/plugins/core/markdown-paste.js [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+
+  // export the resulting nodes as markdown
+  let markdown = ''
+  bridge.update(() => {
+    markdown = $lexicalToMarkdown()
+    $getRoot().clear()
+  })
+
+  return markdown
+}
```
Comment (huumn) [inline components/editor/plugins/core/markdown-paste.js:30]: This bridge is worth its weight in bitcoin.

Comment (Soxasora) [reply components/editor/plugins/core/markdown-paste.js:30]: I was thinking that maybe, like #2870, the bridge should be created and destroyed per each `PASTE_COMMAND`. It's really fast, keeping it there idle feels useless, especially if we consider that there's already one with the toolbar transformations (the transformer bridge) in markdown.
