### PR TITLE
Msats to sats floor

### LINKED ISSUE #1303: Lack of msats support from LNURL providers
**Description**

My SN wallet is above the limit I have set. Went to the attach wallet config page for it and I see many log messages like this.

`13m	[lnAddr]	error	creating invoice for SN: autowithdrawal failed: Error: invoice has incorrect amount`

My wallet is a lightning address type of wallet. This seems to have started about 19 hours ago.

**Steps to Reproduce**

Set up an Alby wallet with lightning address and set your wallet limit. Now receive sats above the limit.

**Expected behavior**

### PR DESCRIPTION
**Pull request by huumn**
fixes #1303

Mostly this floors any msats passed to lnaddr's `createInvoice`. This change also required modify `wrapInvoice` to take the served invoice's msats as a parameter (as it can't be induced anymore). For p2p zaps, the excess msats effectively get paid to SN.

### CODE REVIEW

File: wallets/cln/server.js [hunk 1]
```diff
@@ -3,7 +3,7 @@ import { createInvoice as clnCreateInvoice } from '@/lib/cln'
 export * from 'wallets/cln'
 
 export const testConnectServer = async ({ socket, rune, cert }) => {
-  return await createInvoice({ msats: 1, expiry: 1, description: '' }, { socket, rune, cert })
+  return await createInvoice({ msats: 1000, expiry: 1, description: '' }, { socket, rune, cert })
```
Comment (huumn) [inline wallets/cln/server.js:6]: I also made the test invoice less likely to be rejected for msats reasons.

File: wallets/wrap.js [hunk 2]
```diff
@@ -145,13 +155,13 @@ export default async function wrapInvoice (bolt11, { description, descriptionHas
 
     // validate the fee budget
     const minEstFees = toPositiveNumber(routingFeeMsat)
-    const outgoingMaxFeeMsat = Math.ceil(outgoingMsat * MAX_FEE_ESTIMATE_PERCENT)
+    const outgoingMaxFeeMsat = Math.ceil(msats * MAX_FEE_ESTIMATE_PERCENT)
```
Comment (huumn) [inline wallets/wrap.js:158]: This was always intended to be 2.5% of the incoming amount, so now it is.

File: wallets/server.js [hunk 3]
```diff
@@ -53,7 +53,21 @@ export async function createInvoice (userId, { msats, description, descriptionHa
...
+        }
+        if (BigInt(msats) - BigInt(bolt11.mtokens) >= 1000n) {
+          throw new Error(`invoice has a different satoshi amount ${bolt11.mtokens} !== ${msats}`)
+        }
+
+        await addWalletLog({
+          wallet,
+          level: 'INFO',
+          message: `wallet does not support msats so we floored ${msats} msats to nearest sat ${BigInt(bolt11.mtokens)} msats`
+        }, { models })
```
Comment (ekzyis) [inline wallets/server.js:70]: I like this but I noticed we only have wallet logs if the user invoice creation fails but not if the autowithdrawal itself fails. So then only this log will show up in the logs which looks confusing.

But that's unrelated to this PR, that was already the case since #1178. I'll fix this in another PR.

**Review by ekzyis — APPROVED** [review]
Looks good, only left two comments but not blocking
